language: node_js
node_js: 
    - 13

services: 
    - docker

#pre-testing installs
install: 
    - echo "nothing need to be installed"

#scripts to be run such as tests
before_script: 
    - echo "no tests"

script:
    - docker --version 
    - docker build -t "simple-node" .
    - docker tag simple-node uezima/simple-node:latest

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push uezima/simple-node
